# Generated by Django 4.1 on 2022-10-11 17:22

from django.db import migrations, models
import registration_custom.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Номер сотового')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('status', models.CharField(blank=True, choices=[('На рассмотрении', 'На рассмотрении'), ('Утвержден', 'Утвержден'), ('Отклонен', 'Отклонен')], default='На рассмотрении', max_length=30, null=True, verbose_name='Статус')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Дата авторизации')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
            managers=[
                ('objects', registration_custom.models.MyAccountManager()),
            ],
        ),
    ]
